---
kind: pipeline
type: docker
name: android_kernel_realme_RMX1921_ksb5

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: building
    image: debian:stable-slim
    environment:
      CI_CHANNEL_ID:
        from_secret: ci_channel_id
      BOT_API_KEY:
        from_secret: bot_api_key
      PD_API_KEY:
        from_secret: pd_api_key
      TYPE: "REL-2.0.1"
      DEVICE: alioth
      KBUILD_BUILD_USER: Realme
      KBUILD_BUILD_HOST: XT
    commands:
      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git binutils-gold zip python python3 flex cpio libncurses5-dev wget
      - ld -v
      - git clone https://github.com/Rmx1921/Drone-scripts.git -b newtest script && cd script
      - chmod 777 setup-drone
      - chmod 777 build-kernel
      - ./setup-drone --proton 
      - ./build-kernel --proton --lto
